### ISSUE TITLE
Error setting up dev env containers - nvidia needed??

### ISSUE THREAD

**Issue by kulbinderdio** [purton-tech/fine-tuna#5]
Clone repository and set up VSC
Upon starting VSC asked to start in containers, after several minutes of start up failed with following output

mote-containers/data/docker-compose/docker-compose.devcontainer.containerFeatures-1694508858577.yml up -d
[+] Running 8/8
 ✔ Network fine-tuna_devcontainer_default           Created                0.1s 
 ✔ Volume "fine-tuna_devcontainer_target"           Created                0.0s 
 ✔ Container fine-tuna_devcontainer-unstructured-1  Started                0.0s 
 ✔ Container fine-tuna_devcontainer-envoy-1         Started                0.0s 
 ✔ Container fine-tuna_devcontainer-db-1            Healthy                0.0s 
 ✔ Container fine-tuna_devcontainer-llm-api-1       Started                0.0s 
 ✔ Container fine-tuna_devcontainer-development-1   Created                0.0s 
 ✔ Container fine-tuna_devcontainer-barricade-1     Started                0.0s 
**Error response from daemon: could not select device driver "nvidia" with capabilities: [[gpu]]**
[233903 ms] Error: Command failed: docker compose --project-name fine-tuna_devcontainer -f /home/kdio/dev/fine-tuna/fine-tuna/.devcontainer/docker-compose.yml -f /home/kdio/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data/docker-compose/docker-compose.devcontainer.build-1694508639397.yml -f /home/kdio/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data/docker-compose/docker-compose.devcontainer.containerFeatures-1694508858577.yml up -d
[233903 ms]     at tAA (/home/kdio/.vscode/extensions/ms-vscode-remote.remote-containers-0.309.0/dist/spec-node/devContainersSpecCLI.js:427:3052)
[233903 ms]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[233903 ms]     at async eAA (/home/kdio/.vscode/extensions/ms-vscode-remote.remote-containers-0.309.0/dist/spec-node/devContainersSpecCLI.js:409:3167)
[233903 ms]     at async FAA (/home/kdio/.vscode/extensions/ms-vscode-remote.remote-containers-0.309.0/dist/spec-node/devContainersSpecCLI.js:479:3833)
[233903 ms]     at async GC (/home/kdio/.vscode/extensions/ms-vscode-remote.remote-containers-0.309.0/dist/spec-node/devContainersSpecCLI.js:479:4775)
[233904 ms]     at async VeA (/home/kdio/.vscode/extensions/ms-vscode-remote.remote-containers-0.309.0/dist/spec-node/devContainersSpecCLI.js:611:12240)
[233904 ms]     at async WeA (/home/kdio/.vscode/extensions/ms-vscode-remote.remote-containers-0.309.0/dist/spec-node/devContainersSpecCLI.js:611:11981)
[233907 ms] Exit code 1
[233911 ms] Command failed: /usr/share/code/code --ms-enable-electron-run-as-node /home/kdio/.vscode/extensions/ms-vscode-remote.remote-containers-0.309.0/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /home/kdio/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --container-session-data-folder /tmp/devcontainers-51feb12c-fcba-47b6-8b22-d434e6e3d6941694508635609 --workspace-folder /home/kdio/dev/fine-tuna/fine-tuna --workspace-mount-consistency cached --id-label devcontainer.local_folder=/home/kdio/dev/fine-tuna/fine-tuna --id-label devcontainer.config_file=/home/kdio/dev/fine-tuna/fine-tuna/.devcontainer/devcontainer.json --log-level debug --log-format json --config /home/kdio/dev/fine-tuna/fine-tuna/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[233911 ms] Exit code 1

**Comment by ianpurton** [comment]
The project used to require GPU acceleration but this has been removed. I've updated the devcontainer, can you 
 git pull and try again?
